# Discord Server: 
# Github: https://github.com/XSaitoKungX
# Docs: 
# Dashboard: 

# Created by: XSaitoKungX
# Version: 1.0.0
# Discord: xsaitox

# This file is the main configuration file for the bot.
# Inside this file you will find all the settings you need to configure the bot.
# If you have any questions, please contact us on our discord server.
# If you want to know more about the bot, you can visit our website.

######################
#   CONFIG GENERAL   #
######################

general:
   token: '' # The bot token in Discord Developers --> https://discord.com/developers/applications
   administrator: '' # ID of the bot administrator and server owner
   customers: '' # ID of the buyers' role
   owners: '' # Owners with access to premium commands
   licence: ''
   server: '' # Main server where the bot will be located
   channel: '' # Main channel of the bot
   shards:
      total: 1
      respawn: true
   ip: '' # 78.108.218.63
   port: '' # 25507

databases:
   mongoose: '' # Link to the Mongoose database is explained in the following section --> https://cloud.mongodb.com/

dashboard:
   enabled: false
   host: '' #Server IP for bot to connect to
   port: 3000 #server port for bot to connect to
   username: '' #email for bot
   password: '' #password for bot
   version: '' #version of server bot is trying to connect to
   channel: '' #channel log for bot
   production: true

######################
#   CONFIG DISCORD   #
######################

settings:
  prefix: '' # Command prefix
  color: '' # Embed color
  discord: '' # Discord server invite link
  channel: '' # Main channel
  minecraft:
    ip: '' # IP of your Minecraft Java server
    port: '' # Port (optional)

webhooks:
  errors: '' # Webhook link for error logs
  commands: '' # Webhook link for used commands
  logs: '' # Webhook link for main logs

modmail:
  enabled: true # Modmail enabled or disabled
  guildId: '' # Server ID where this feature will operate
  categoryId: '' # Category for generated tickets
  staffRoles: '' # Staff role ID to handle
  mentionStaffRolesOnNewMail: true # Mention staff or not on new mail

######################
# CONFIG INTEGRATION #
######################

manager:
   enabled: false
   channel_id: ''
   message_id: ''

######################
#   CONFIG EVENTOS   #
######################

events:
  farewells:
    color: '' # Farewell color
    subcolor: '' # Subcolor of messages
    channel: '' # Channel ID where messages will be sent
    embeds:
      color: '' # Color of farewell embeds
      author: '' # Author of messages
  welcomes:
    color: '' # Welcome color
    subcolor: '' # Subcolor of messages
    channel: '' # Channel ID where messages will be sent
    embeds:
      color: '' # Color of welcome embeds
      author: '' # Author of messages
  admin_logs: '' # ID of the admin command log channel
  command_logs: '' # ID of the command used log channel

######################
#   CONFIG TICKETS   #
######################

tickets:
  placeholders: '' # Text for the ticket menu
  options: # Menu options like services, support, reports, etc.
    option_1: ''
    option_2: ''
    option_3: ''
    option_4: ''
    option_5: ''
    option_6: ''
    option_7: ''
  description: # Descriptions for the menu options
    option_1: ''
    option_2: ''
    option_3: ''
    option_4: ''
    option_5: ''
    option_6: ''
    option_7: ''
    option_8: ''

######################
#   CONFIG SETUPS    #
######################

# ID of the channel where reviews will be sent
setups:
  levels:
    enabled: false
    channel: ''
  rooms:
    enabled: true
    channel: ''
  boost:
    enabled: true
    channel: ''
  anime:
    enabled: false
    channel: ''
  nsfw:
    enabled: false
    channel: ''
  meme:
    enabled: false
    channel: ''
  startboard:
    enabled: true
    channel: ''
  reviews: ''

######################
#   CONFIG AUTOMOD   #
######################

# ID of the log channels
automods:
  channel: ''
  antibot:
    enabled: false
    channel: ''
  channels:
    enabled: false
    action: ''
    message: ''
  invites:
    enabled: false
    action: ''
    message: ''
  ghostDetector:
    enabled: false
    channel: ''
    time: 10000
  scamDetector:
    enabled: false
    channel: ''

######################
#   CONFIG MODALS    #
######################

modals:
  global: ''
  bugs: ''
  private: ''
  classes: ''
  suggestions: ''
  ratings: ''